### PR TITLE
 Enforce the fundamental Green function properties for G0_iw and G_iw

### PR DESCRIPTION
**Pull request by Wentzell**
We now enforce the fundamental Green function property `G[iw](i,j) = G[-iw](j,i)*`
for both the solver-input S.G0_iw as well as the solver output S.G_iw.
If the input violates the relation a warning will be issued and the input will
be automatically symmetrized. The output will always be symmetrized and the
symmetry violation `G[iw](i,j) -  G[-iw](j,i)` is stored in S.hermiticity_violation_G_iw

This change was discussed with @parcollet @mzingl

### CODE REVIEW

**Comment by mzingl** [comment]
I checked the changes and it looks fine to me.
Nils, thanks for adding this!

**Comment by HugoStrand** [comment]
Dear all,

This is fine, in principle. But, it changes behavior of the solver and it will hide ergodicity problems in the sampling from the user. Especially since there is no warning if the sampled Gf breaks hermiticity (too much).

I would vote for a more conservative approach and replace the automatic symmetrization of the sampled Gf with a small tutorial on how to symmetrize the result by hand.

Cheers, Hugo

**Comment by mzingl** [comment]
I like that now both, the 'corrected' G_iw and the raw G_iw_raw are available to the user.
What about writing a warning if the G_iw_raw violates (too much) the hermiticity?
This warning should say that G_iw is symmetrized and that the raw data is available as G_iw_raw.

**Comment by Wentzell** [comment]
@the-hampel Please review the latest changes and update the documentation as discussed.

**Comment by the-hampel** [comment]
I added some parts in the documentation in the solve function of the solver. I hope this sits at the right spot now. Please check, otherwise I will iterate on it. The other changes look good! For me atm the test py_slater fails because `assert is_gf_hermitian(self.G_iw)` is triggered ( line 143 in solve function. I am not quite sure if this is a problem with my test but. Do the tests work all for you?

**Pull request merged**
